In [1]:
from excel import read_excel
import error
import os

In [2]:
col_alias_df, _ = read_excel(os.path.join('input', 'mosfets.xlsx'), replace_nan='', sheet_name='column_aliases' )

In [3]:
col_alias_df

,alias,col_name,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,pr,Ispn,,,,,,,,,,,,,,,,
1,ds,Data Sheet,,,,,,,,,,,,,,,,
2,st,OpnStatus,,,,,,,,,,,,,,,,
3,pg,Package,,,,,,,,,,,,,,,,
4,ty,Type,,,,,,,,,,,,,,,,
5,vds,V<sub>DS</sub>,,,,,,,,,,,,,,,,
6,id,I<sub>D </sub>,,,,,,,,,,,,,,,,
7,rdson,R<sub>DS (on)</sub>,,,,,,,,,,,,,,,,
8,vgs,V<sub>GS(th)</sub>,,,,,,,,,,,,,,,,
9,to,Topology,,,,,,,,,,,,,,,,
10,te,Technology,,,,,,,,,,,,,,,,
11,qu,Qualification,,,,,,,,,,,,,,,,
12,bp,Budgetary Price €/1k,,,,,,,,,,,,,,,,
13,np,new_product,,,,,,,,,,,,,,,,
14,pp,ProductPageUrl,,,,,,,,,,,,,,,,
15,ho,Housing,,,,,,,,,,,,,,,,
16,other,Q<sub>G</sub>,Q<sub>G</sub> @4.5V,Q<sub>G</sub> typ @10V,Q<sub>G</sub> typ @4.5V,Q<sub>G</sub> typical,Q<sub>gd</sub>,Q<sub>gd</sub> typ,R<sub>DS (on)</sub> @ Tj = 25°C,R<sub>DS (on)</sub> @1.8V,R<sub>DS (on)</sub> @10V,R<sub>DS (on)</sub> @2.5V,R<sub>DS (on)</sub> @2.7V,R<sub>DS (on)</sub> @4.5V,R<sub>DS (on)</sub> @4.5V LL,R<sub>G</sub>,R<sub>Gint</sub>,R<sub>th</sub>
17,ap,Applications,,,,,,,,,,,,,,,,

In [4]:
col_alias_df = col_alias_df.set_index('alias')

In [40]:
for colname, colvalues in col_alias_df.iteritems():
    for index, val in colvalues.items():
        print(index, val)

pr Ispn
ds Data Sheet
st OpnStatus
pg Package
ty Type
vds V<sub>DS</sub>
id I<sub>D </sub>
rdson R<sub>DS (on)</sub>
vgs V<sub>GS(th)</sub>
to Topology
te Technology
qu Qualification
bp Budgetary Price €/1k
np new_product
pp ProductPageUrl
ho Housing
other Q<sub>G</sub>
ap Applications
pr
ds
st
pg
ty
vds
id
rdson
vgs
to
te
qu
bp
np
pp
ho
other Q<sub>G</sub> @4.5V
ap
pr
ds
st
pg
ty
vds
id
rdson
vgs
to
te
qu
bp
np
pp
ho
other Q<sub>G</sub> typ @10V
ap
pr
ds
st
pg
ty
vds
id
rdson
vgs
to
te
qu
bp
np
pp
ho
other Q<sub>G</sub> typ @4.5V
ap
pr
ds
st
pg
ty
vds
id
rdson
vgs
to
te
qu
bp
np
pp
ho
other Q<sub>G</sub> typical
ap
pr
ds
st
pg
ty
vds
id
rdson
vgs
to
te
qu
bp
np
pp
ho
other Q<sub>gd</sub>
ap
pr
ds
st
pg
ty
vds
id
rdson
vgs
to
te
qu
bp
np
pp
ho
other Q<sub>gd</sub> typ
ap
pr
ds
st
pg
ty
vds
id
rdson
vgs
to
te
qu
bp
np
pp
ho
other R<sub>DS (on)</sub> @ Tj = 25°C
ap
pr
ds
st
pg
ty
vds
id
rdson
vgs
to
te
qu
bp
np
pp
ho
other R<sub>DS (on)</sub> @1.8V
ap
pr
ds
st
pg
ty
vds
id
rdson
vgs
to
te
qu
bp
np
pp
ho
other R<sub>DS (on)</sub> @10V
ap
pr
ds
st
pg
ty
vds
id
rdson
vgs
to
te
qu
bp
np
pp
ho
other R<sub>DS (on)</sub> @2.5V
ap
pr
ds
st
pg
ty
vds
id
rdson
vgs
to
te
qu
bp
np
pp
ho
other R<sub>DS (on)</sub> @2.7V
ap
pr
ds
st
pg
ty
vds
id
rdson
vgs
to
te
qu
bp
np
pp
ho
other R<sub>DS (on)</sub> @4.5V
ap
pr
ds
st
pg
ty
vds
id
rdson
vgs
to
te
qu
bp
np
pp
ho
other R<sub>DS (on)</sub> @4.5V LL
ap
pr
ds
st
pg
ty
vds
id
rdson
vgs
to
te
qu
bp
np
pp
ho
other R<sub>G</sub>
ap
pr
ds
st
pg
ty
vds
id
rdson
vgs
to
te
qu
bp
np
pp
ho
other R<sub>Gint</sub>
ap
pr
ds
st
pg
ty
vds
id
rdson
vgs
to
te
qu
bp
np
pp
ho
other R<sub>th</sub>
ap
pr ttt
ds ttt
st ttt
pg ttt
ty ttt
vds ttt
id ttt
rdson ttt
vgs ttt
to ttt
te ttt
qu ttt
bp ttt
np ttt
pp ttt
ho ttt
other ttt
ap ttt

In [15]:
col_alias_df['pppp'] = 'ttt'

In [55]:
d = {}
for index, row in col_alias_df.iterrows():
    row = [r for r in row if len(r) > 0]
    if len(row) == 1:
        row = row[0]
    if len(row) == 0:
        row=''
    d.update({index: row})

In [56]:
d

{'pr': 'Ispn',
 'ds': 'Data Sheet',
 'st': 'OpnStatus',
 'pg': ['Package', 'iii'],
 'ty': 'Type',
 'vds': 'V<sub>DS</sub>',
 'id': 'I<sub>D </sub>',
 'rdson': 'R<sub>DS (on)</sub>',
 'vgs': 'V<sub>GS(th)</sub>',
 'to': 'Topology',
 'te': 'Technology',
 'qu': 'Qualification',
 'bp': 'Budgetary Price \x80€/1k',
 'np': ['new_product', 'eee', 'ffff'],
 'ww': ''}

In [57]:
isinstance(d['np'], list)

True

In [58]:
l = [1,2,3]

In [59]:
l.extend([5,6,7])

In [60]:
l

[1, 2, 3, 5, 6, 7]

In [62]:
l = l + '666'

TypeError: can only concatenate list (not "str") to list

In [1]:
import datetime

In [7]:
date_time_str1 = '2019-07-01T00:00:00+02:00'
date_time_obj1 = datetime.datetime.strptime("ssss", '%Y-%m-%d')

date_time_str2 = '2020-08-01T00:00:00+02:00'
date_time_obj2 = datetime.datetime.strptime(date_time_str2[:10], '%Y-%m-%d')

today = datetime.datetime.today()

ValueError: time data 'ssss' does not match format '%Y-%m-%d'

In [6]:
(date_time_obj1-today).days

-33

In [2]:
datetime.datetime.today()

datetime.datetime(2019, 8, 2, 22, 6, 11, 467618)